# Generated by Django 5.2.17 on 2026-09-02 20:09

import apps.organizacoes.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0003_criar_grupos_iniciais'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nipc', models.CharField(max_length=9, unique=True, validators=[apps.organizacoes.validators.validar_nipc])),
                ('denominacao_legal', models.CharField(max_length=255, verbose_name='denominação legal')),
                ('nome_comercial', models.CharField(blank=True, max_length=255)),
                ('natureza_juridica', models.CharField(blank=True, max_length=120, verbose_name='natureza jurídica')),
                ('cae_principal', models.CharField(blank=True, max_length=10, verbose_name='CAE principal')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('morada', models.CharField(blank=True, max_length=255)),
                ('codigo_postal', models.CharField(blank=True, max_length=20, verbose_name='código postal')),
                ('localidade', models.CharField(blank=True, max_length=120)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ('denominacao_legal',),
            },
        ),
        migrations.CreateModel(
            name='EntidadeFormadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nipc', models.CharField(max_length=9, unique=True, validators=[apps.organizacoes.validators.validar_nipc])),
                ('denominacao_legal', models.CharField(max_length=255, verbose_name='denominação legal')),
                ('nome_comercial', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('morada', models.CharField(blank=True, max_length=255)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'entidade formadora',
                'verbose_name_plural': 'entidades formadoras',
                'ordering': ('denominacao_legal',),
            },
        ),
        migrations.CreateModel(
            name='CertificacaoFormadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('enquadramento', models.CharField(choices=[('CERTIFICADA_DGERT', 'Certificada pela DGERT'), ('DISPENSADA', 'Dispensada de certificação'), ('PENDENTE_CONFIRMACAO', 'Pendente de confirmação')], max_length=24)),
                ('area_codigo', models.CharField(blank=True, max_length=20, verbose_name='código da área')),
                ('area_designacao', models.CharField(blank=True, max_length=255, verbose_name='designação da área')),
                ('numero_certificacao', models.CharField(blank=True, max_length=100, verbose_name='número da certificação')),
                ('valida_desde', models.DateField(blank=True, null=True)),
                ('valida_ate', models.DateField(blank=True, null=True)),
                ('verificada_em', models.DateTimeField(blank=True, null=True)),
                ('verificada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificacoes_formadoras_verificadas', to=settings.AUTH_USER_MODEL)),
                ('entidade_formadora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificacoes', to='organizacoes.entidadeformadora')),
            ],
            options={
                'verbose_name': 'certificação de entidade formadora',
                'verbose_name_plural': 'certificações de entidades formadoras',
                'ordering': ('entidade_formadora', 'area_codigo', '-valida_desde'),
            },
        ),
        migrations.CreateModel(
            name='ContaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('iban_cifrado', models.TextField(editable=False)),
                ('iban_hash', models.CharField(db_index=True, editable=False, max_length=64)),
                ('iban_ultimos_4', models.CharField(editable=False, max_length=4)),
                ('nome_titular', models.CharField(max_length=255)),
                ('principal', models.BooleanField(default=False)),
                ('ativa', models.BooleanField(default=True)),
                ('validada_em', models.DateTimeField(blank=True, null=True)),
                ('candidato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagamento', to='contas.perfilcandidato')),
                ('validada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagamento_validadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagamento', to='organizacoes.empresa')),
            ],
            options={
                'verbose_name': 'conta de pagamento',
                'verbose_name_plural': 'contas de pagamento',
                'ordering': ('nome_titular',),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('candidato__isnull', False), ('empresa__isnull', True)), models.Q(('candidato__isnull', True), ('empresa__isnull', False)), _connector='OR'), name='organizacoes_conta_um_proprietario'), models.UniqueConstraint(condition=models.Q(('ativa', True), ('principal', True)), fields=('candidato',), name='organizacoes_conta_principal_candidato_unica'), models.UniqueConstraint(condition=models.Q(('ativa', True), ('principal', True)), fields=('empresa',), name='organizacoes_conta_principal_empresa_unica')],
            },
        ),
        migrations.CreateModel(
            name='AssociacaoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('papel', models.CharField(choices=[('GESTOR', 'Gestor'), ('RECURSOS_HUMANOS', 'Recursos humanos'), ('CONSULTA', 'Consulta')], max_length=20)),
                ('ativa', models.BooleanField(default=True)),
                ('inicio_em', models.DateTimeField()),
                ('fim_em', models.DateTimeField(blank=True, null=True)),
                ('concedida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associacoes_empresa_concedidas', to=settings.AUTH_USER_MODEL)),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='associacoes_empresa', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='associacoes', to='organizacoes.empresa')),
            ],
            options={
                'verbose_name': 'associação a empresa',
                'verbose_name_plural': 'associações a empresas',
                'ordering': ('empresa', 'utilizador', 'papel'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('ativa', True)), fields=('utilizador', 'empresa', 'papel'), name='organizacoes_associacao_ativa_unica'), models.CheckConstraint(condition=models.Q(('fim_em__isnull', True), ('fim_em__gte', models.F('inicio_em')), _connector='OR'), name='organizacoes_associacao_periodo_valido')],
            },
        ),
        migrations.CreateModel(
            name='VinculoLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('situacao', models.CharField(choices=[('CONTA_OUTREM', 'Trabalhador por conta de outrem'), ('CONTA_PROPRIA', 'Trabalhador por conta própria'), ('DESEMPREGADO', 'Desempregado')], max_length=20, verbose_name='situação')),
                ('inicio_em', models.DateField()),
                ('fim_em', models.DateField(blank=True, null=True)),
                ('inscricao_iefp_em', models.DateField(blank=True, null=True, verbose_name='inscrição no IEFP')),
                ('nivel_qualificacao', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='nível de qualificação')),
                ('confirmado_em', models.DateTimeField(blank=True, null=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_laborais', to='contas.perfilcandidato')),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculos_laborais_confirmados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_laborais', to='organizacoes.empresa')),
            ],
            options={
                'verbose_name': 'vínculo laboral',
                'verbose_name_plural': 'vínculos laborais',
                'ordering': ('-inicio_em',),
                'constraints': [models.CheckConstraint(condition=models.Q(('fim_em__isnull', True), ('fim_em__gte', models.F('inicio_em')), _connector='OR'), name='organizacoes_vinculo_periodo_valido'), models.CheckConstraint(condition=models.Q(models.Q(models.Q(('situacao', 'CONTA_OUTREM'), _negated=True), ('empresa__isnull', False), _connector='OR'), models.Q(models.Q(('situacao', 'DESEMPREGADO'), _negated=True), ('empresa__isnull', True), _connector='OR')), name='organizacoes_vinculo_empresa_coerente')],
            },
        ),
    ]
