# Generated by Django 5.2.17 on 2026-09-02 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '__first__'),
        ('organizacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificacaoformadora',
            name='evidencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificacoes_formadoras_comprovadas', to='documentos.versaodocumento'),
        ),
        migrations.AddField(
            model_name='contapagamento',
            name='comprovativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagamento_comprovadas', to='documentos.versaodocumento'),
        ),
        migrations.AddField(
            model_name='vinculolaboral',
            name='evidencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_laborais_comprovados', to='documentos.versaodocumento'),
        ),
    ]
