# Generated by Django 5.2.17 on 2026-09-03 08:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidaturas', '0003_participacaoformacao_motivo_resultado'),
        ('documentos', '0002_snapshotsubmissao_transicao'),
        ('regras', '0001_initial'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApoioFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('FORMACAO', 'Formação'), ('BOLSA', 'Bolsa de formação'), ('REFEICAO', 'Subsídio de refeição'), ('TRANSPORTE', 'Transporte coletivo')], max_length=12)),
                ('custo_declarado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('financiamento_terceiros', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('valor_elegivel', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_aprovado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_final', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('moeda', models.CharField(default='EUR', max_length=3)),
                ('estado', models.CharField(choices=[('SEM_APOIO', 'Sem apoio'), ('ESTIMADO', 'Estimado'), ('APROVADO', 'Aprovado'), ('PRIMEIRA_PRESTACAO_PENDENTE', 'Primeira prestação pendente'), ('PARCIALMENTE_PAGO', 'Parcialmente pago'), ('PAGAMENTO_FINAL_PENDENTE', 'Pagamento final pendente'), ('PAGO', 'Pago'), ('RESTITUICAO_PENDENTE', 'Restituição pendente'), ('RESTITUIDO', 'Restituído'), ('REGULARIZADO', 'Regularizado')], default='ESTIMADO', editable=False, max_length=32)),
                ('decomposicao_calculo', models.JSONField(blank=True, default=dict)),
                ('calculado_em', models.DateTimeField(blank=True, null=True)),
                ('confirmado_em', models.DateTimeField(blank=True, null=True)),
                ('referencia_externa', models.CharField(blank=True, max_length=100)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apoios_financeiros', to='candidaturas.beneficiariocandidatura')),
                ('calculado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apoios_financeiros_calculados', to=settings.AUTH_USER_MODEL)),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apoios_financeiros_confirmados', to=settings.AUTH_USER_MODEL)),
                ('conjunto_regras', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apoios_financeiros', to='regras.conjuntoregras')),
                ('evidencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apoios_financeiros_comprovados', to='documentos.versaodocumento')),
                ('participacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apoios_financeiros', to='candidaturas.participacaoformacao')),
            ],
            options={
                'verbose_name': 'apoio financeiro',
                'verbose_name_plural': 'apoios financeiros',
                'ordering': ('beneficiario_id', 'participacao_id', 'tipo'),
            },
        ),
        migrations.CreateModel(
            name='MovimentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('PRIMEIRA_PRESTACAO', 'Primeira prestação'), ('REMANESCENTE', 'Remanescente'), ('AJUSTE', 'Ajuste'), ('DEVOLUCAO', 'Devolução')], max_length=20)),
                ('direcao', models.CharField(choices=[('CREDITO', 'Crédito'), ('DEBITO', 'Débito')], max_length=8)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('previsto_para', models.DateTimeField(blank=True, null=True)),
                ('efetivado_em', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PREVISTO', 'Previsto'), ('CONFIRMADO', 'Confirmado'), ('FALHOU', 'Falhou'), ('CANCELADO', 'Cancelado'), ('REGULARIZADO', 'Regularizado')], max_length=12)),
                ('referencia_externa', models.CharField(blank=True, max_length=100)),
                ('chave_idempotencia', models.CharField(max_length=100)),
                ('apoio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='financeiro.apoiofinanceiro')),
                ('comprovativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_financeiros_comprovados', to='documentos.versaodocumento')),
                ('registado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_financeiros_registados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'movimento financeiro',
                'verbose_name_plural': 'movimentos financeiros',
                'ordering': ('apoio_id', 'previsto_para', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Restituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('notificada_em', models.DateTimeField()),
                ('data_limite', models.DateTimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PARCIAL', 'Parcial'), ('PAGA', 'Paga'), ('DISPENSADA', 'Dispensada'), ('REGULARIZADA', 'Regularizada')], default='PENDENTE', editable=False, max_length=12)),
                ('valor_restituido', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('regularizada_em', models.DateTimeField(blank=True, null=True)),
                ('referencia_externa', models.CharField(blank=True, max_length=100)),
                ('chave_idempotencia', models.CharField(max_length=100)),
                ('beneficiario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='restituicoes', to='candidaturas.beneficiariocandidatura')),
                ('candidatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restituicoes', to='candidaturas.candidatura')),
                ('evidencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='restituicoes_comprovadas', to='documentos.versaodocumento')),
                ('prazo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='restituicao', to='workflow.prazo')),
                ('registada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restituicoes_registadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'restituição',
                'verbose_name_plural': 'restituições',
                'ordering': ('data_limite', 'pk'),
            },
        ),
        migrations.AddIndex(
            model_name='apoiofinanceiro',
            index=models.Index(fields=['estado', 'tipo'], name='fin_apoio_estado_tipo_idx'),
        ),
        migrations.AddConstraint(
            model_name='apoiofinanceiro',
            constraint=models.UniqueConstraint(condition=models.Q(('participacao__isnull', False)), fields=('participacao', 'tipo'), name='fin_apoio_participacao_tipo_unico'),
        ),
        migrations.AddConstraint(
            model_name='apoiofinanceiro',
            constraint=models.UniqueConstraint(condition=models.Q(('participacao__isnull', True)), fields=('beneficiario', 'tipo'), name='fin_apoio_beneficiario_tipo_global_unico'),
        ),
        migrations.AddConstraint(
            model_name='apoiofinanceiro',
            constraint=models.CheckConstraint(condition=models.Q(('financiamento_terceiros__gte', 0)), name='fin_apoio_terceiros_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='apoiofinanceiro',
            constraint=models.CheckConstraint(condition=models.Q(('custo_declarado__isnull', True), ('custo_declarado__gte', 0), _connector='OR'), name='fin_apoio_custo_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='apoiofinanceiro',
            constraint=models.CheckConstraint(condition=models.Q(('valor_elegivel__isnull', True), ('valor_elegivel__gte', 0), _connector='OR'), name='fin_apoio_elegivel_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='apoiofinanceiro',
            constraint=models.CheckConstraint(condition=models.Q(('valor_estimado__isnull', True), ('valor_estimado__gte', 0), _connector='OR'), name='fin_apoio_estimado_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='apoiofinanceiro',
            constraint=models.CheckConstraint(condition=models.Q(('valor_aprovado__isnull', True), ('valor_aprovado__gte', 0), _connector='OR'), name='fin_apoio_aprovado_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='apoiofinanceiro',
            constraint=models.CheckConstraint(condition=models.Q(('valor_final__isnull', True), ('valor_final__gte', 0), _connector='OR'), name='fin_apoio_final_nao_negativo'),
        ),
        migrations.AddIndex(
            model_name='movimentofinanceiro',
            index=models.Index(fields=['estado', 'efetivado_em'], name='fin_mov_estado_data_idx'),
        ),
        migrations.AddConstraint(
            model_name='movimentofinanceiro',
            constraint=models.UniqueConstraint(fields=('apoio', 'chave_idempotencia'), name='fin_mov_apoio_idempotencia_unica'),
        ),
        migrations.AddConstraint(
            model_name='movimentofinanceiro',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='fin_mov_valor_positivo'),
        ),
        migrations.AddConstraint(
            model_name='restituicao',
            constraint=models.UniqueConstraint(fields=('candidatura', 'chave_idempotencia'), name='fin_restituicao_idempotencia_unica'),
        ),
        migrations.AddConstraint(
            model_name='restituicao',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='fin_rest_valor_positivo'),
        ),
        migrations.AddConstraint(
            model_name='restituicao',
            constraint=models.CheckConstraint(condition=models.Q(('valor_restituido__gte', 0)), name='fin_rest_restituido_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='restituicao',
            constraint=models.CheckConstraint(condition=models.Q(('data_limite__gte', models.F('notificada_em'))), name='fin_rest_limite_valido'),
        ),
    ]
