# Generated by Django 5.2.17 on 2026-09-02 19:21

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('nome_proprio', models.CharField(max_length=150, verbose_name='nome próprio')),
                ('apelido', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(db_column='ativo', default=True, verbose_name='ativo')),
                ('equipa_interna', models.BooleanField(default=False, help_text='Indica uma conta operacional interna do Forma Flow.')),
                ('is_staff', models.BooleanField(default=False, help_text='Permite entrar na administração técnica do Django.', verbose_name='acesso à administração técnica')),
                ('last_login', models.DateTimeField(blank=True, db_column='ultimo_acesso_em', null=True, verbose_name='último acesso')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilizador',
                'verbose_name_plural': 'utilizadores',
                'ordering': ('email',),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='contas_utilizador_email_ci_unique')],
            },
        ),
    ]
