# Generated by Django 5.2.17 on 2026-09-02 19:22

import apps.contas.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nif', models.CharField(max_length=9, unique=True, validators=[apps.contas.validators.validar_nif])),
                ('data_nascimento', models.DateField(validators=[apps.contas.validators.validar_data_nao_futura], verbose_name='data de nascimento')),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('nacionalidade', models.CharField(blank=True, max_length=2, validators=[django.core.validators.RegexValidator(message='Introduza um código de país ISO com duas letras maiúsculas.', regex='^[A-Z]{2}$')])),
                ('morada', models.CharField(blank=True, max_length=255)),
                ('codigo_postal', models.CharField(blank=True, max_length=20, verbose_name='código postal')),
                ('localidade', models.CharField(blank=True, max_length=120)),
                ('pais', models.CharField(blank=True, max_length=2, validators=[django.core.validators.RegexValidator(message='Introduza um código de país ISO com duas letras maiúsculas.', regex='^[A-Z]{2}$')], verbose_name='país')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('utilizador', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='perfil_candidato', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de candidato',
                'verbose_name_plural': 'perfis de candidato',
                'ordering': ('utilizador__nome_proprio', 'utilizador__apelido'),
                'constraints': [models.CheckConstraint(condition=models.Q(('nif__regex', '^\\d{9}$')), name='contas_perfil_nif_nove_digitos')],
            },
        ),
    ]
