# Generated by Django 5.2.17 on 2026-09-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_criar_grupos_iniciais'),
    ]

    operations = [
        migrations.CreateModel(
            name='TentativaAutenticacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(editable=False, max_length=64, unique=True)),
                ('falhas', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('janela_iniciada_em', models.DateTimeField(editable=False)),
                ('bloqueado_ate', models.DateTimeField(blank=True, editable=False, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tentativa de autenticação',
                'verbose_name_plural': 'tentativas de autenticação',
                'indexes': [models.Index(fields=['bloqueado_ate'], name='contas_login_bloqueio_idx')],
            },
        ),
    ]
