# Generated by Django 5.2.17 on 2026-09-02 22:09

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidaturas', '0002_verificacaoelegibilidade_evidencia'),
        ('documentos', '0001_initial'),
        ('regras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoElementos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fase', models.CharField(choices=[('ANALISE', 'Análise'), ('ENCERRAMENTO', 'Encerramento')], max_length=12)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, verbose_name='referência externa')),
                ('recebido_em', models.DateTimeField()),
                ('data_limite', models.DateTimeField()),
                ('estado', models.CharField(choices=[('ABERTO', 'Aberto'), ('RESPOSTA_RASCUNHO', 'Resposta em rascunho'), ('RESPONDIDO', 'Respondido'), ('FECHADO', 'Fechado'), ('EXPIRADO', 'Expirado'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=20)),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
                ('candidatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_elementos', to='candidaturas.candidatura')),
                ('evidencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_elementos_comprovados', to='documentos.versaodocumento')),
                ('registado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_elementos_registados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pedido de elementos',
                'verbose_name_plural': 'pedidos de elementos',
                'ordering': ('-recebido_em', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='PedidoEncerramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('PREPARACAO', 'Preparação'), ('SUBMETIDO', 'Submetido'), ('EM_ANALISE', 'Em análise'), ('AGUARDA_ELEMENTOS', 'Aguarda elementos'), ('CONCLUIDO', 'Concluído'), ('NAO_ACEITE', 'Não aceite')], default='PREPARACAO', max_length=20)),
                ('preparacao_iniciada_em', models.DateTimeField()),
                ('submetido_em', models.DateTimeField(blank=True, null=True)),
                ('analise_iniciada_em', models.DateTimeField(blank=True, null=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, verbose_name='referência externa')),
                ('resultado_final', models.CharField(blank=True, choices=[('CONCLUIDO', 'Concluído'), ('CONCLUIDO_PARCIAL', 'Concluído parcialmente'), ('NAO_ACEITE', 'Não aceite'), ('OUTRO', 'Outro')], max_length=20)),
                ('observacoes_decisao', models.TextField(blank=True, verbose_name='observações da decisão')),
                ('candidatura', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pedido_encerramento', to='candidaturas.candidatura')),
                ('snapshot_submissao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_encerramento', to='documentos.snapshotsubmissao')),
            ],
            options={
                'verbose_name': 'pedido de encerramento',
                'verbose_name_plural': 'pedidos de encerramento',
            },
        ),
        migrations.CreateModel(
            name='Prazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('DECISAO', 'Decisão'), ('RESPOSTA_ELEMENTOS', 'Resposta a elementos'), ('TERMO', 'Termo'), ('PRIMEIRA_PRESTACAO', 'Primeira prestação'), ('REMANESCENTE', 'Remanescente'), ('ENCERRAMENTO', 'Encerramento'), ('RESTITUICAO', 'Restituição'), ('OUTRO', 'Outro')], max_length=20)),
                ('codigo_regra', models.CharField(max_length=40, verbose_name='código da regra')),
                ('inicio_em', models.DateTimeField()),
                ('unidade', models.CharField(choices=[('DIAS_UTEIS', 'Dias úteis'), ('DIAS_CONSECUTIVOS', 'Dias consecutivos'), ('MESES', 'Meses'), ('ANOS', 'Anos')], max_length=20)),
                ('duracao', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='duração')),
                ('limite_calculado', models.DateTimeField()),
                ('limite_oficial', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ATIVO', 'Ativo'), ('SUSPENSO', 'Suspenso'), ('CUMPRIDO', 'Cumprido'), ('EXPIRADO', 'Expirado'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=10)),
                ('motivo_correcao', models.TextField(blank=True, verbose_name='motivo da correção')),
                ('limite_anterior', models.DateTimeField(blank=True, null=True)),
                ('beneficiario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prazos', to='candidaturas.beneficiariocandidatura')),
                ('candidatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prazos', to='candidaturas.candidatura')),
                ('conjunto_regras', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prazos', to='regras.conjuntoregras')),
                ('corrigido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prazos_corrigidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'prazo',
                'verbose_name_plural': 'prazos',
                'ordering': ('limite_calculado', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='QuestaoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField()),
                ('texto', models.TextField()),
                ('destinatario', models.CharField(choices=[('TITULAR', 'Titular'), ('BENEFICIARIO', 'Beneficiário'), ('EMPRESA', 'Empresa'), ('FORMADORA', 'Entidade formadora'), ('GESTOR', 'Gestor')], max_length=14)),
                ('exige_texto', models.BooleanField(default=True)),
                ('exige_documento', models.BooleanField(default=False)),
                ('obrigatoria', models.BooleanField(default=True)),
                ('beneficiario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questoes_pedido', to='candidaturas.beneficiariocandidatura')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questoes', to='workflow.pedidoelementos')),
                ('tipo_documento_pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questoes_pedido', to='regras.tipodocumento')),
            ],
            options={
                'verbose_name': 'questão de pedido',
                'verbose_name_plural': 'questões de pedidos',
                'ordering': ('pedido', 'ordem'),
            },
        ),
        migrations.CreateModel(
            name='RespostaQuestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(editable=False)),
                ('texto', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('SUBMETIDA', 'Submetida'), ('SUBSTITUIDA', 'Substituída')], default='RASCUNHO', max_length=12)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('submetida_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas_questoes', to=settings.AUTH_USER_MODEL)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='workflow.questaopedido')),
                ('versoes_documentos', models.ManyToManyField(blank=True, related_name='respostas_questoes', to='documentos.versaodocumento')),
            ],
            options={
                'verbose_name': 'resposta a questão',
                'verbose_name_plural': 'respostas a questões',
                'ordering': ('questao', '-numero'),
            },
        ),
        migrations.CreateModel(
            name='SuspensaoPrazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_em', models.DateTimeField()),
                ('fim_em', models.DateTimeField(blank=True, null=True)),
                ('origem', models.CharField(choices=[('CALCULADA', 'Calculada'), ('OFICIAL', 'Oficial'), ('CORRECAO_MANUAL', 'Correção manual')], max_length=16)),
                ('motivo', models.TextField()),
                ('registada_em', models.DateTimeField(auto_now_add=True)),
                ('pedido_elementos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suspensoes_prazo', to='workflow.pedidoelementos')),
                ('prazo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suspensoes', to='workflow.prazo')),
                ('registada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspensoes_prazo_registadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'suspensão de prazo',
                'verbose_name_plural': 'suspensões de prazos',
                'ordering': ('prazo', 'inicio_em'),
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(max_length=80)),
                ('titulo', models.CharField(max_length=255, verbose_name='título')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('estado', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_EXECUCAO', 'Em execução'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=12)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='NORMAL', max_length=8)),
                ('data_limite', models.DateTimeField(blank=True, null=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('chave_deduplicacao', models.CharField(blank=True, max_length=150, null=True)),
                ('atribuida_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_atribuidas', to=settings.AUTH_USER_MODEL)),
                ('beneficiario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarefas', to='candidaturas.beneficiariocandidatura')),
                ('candidatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarefas', to='candidaturas.candidatura')),
                ('concluida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_concluidas', to=settings.AUTH_USER_MODEL)),
                ('encerramento_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarefas', to='workflow.pedidoencerramento')),
                ('pedido_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarefas', to='workflow.pedidoelementos')),
                ('prazo_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarefas', to='workflow.prazo')),
                ('requisito_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarefas', to='documentos.requisitodocumento')),
            ],
            options={
                'verbose_name': 'tarefa',
                'verbose_name_plural': 'tarefas',
                'ordering': ('-prioridade', 'data_limite', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=80, verbose_name='código')),
                ('titulo', models.CharField(max_length=255, verbose_name='título')),
                ('mensagem', models.TextField()),
                ('prioridade', models.CharField(choices=[('INFORMATIVA', 'Informativa'), ('ATENCAO', 'Atenção'), ('URGENTE', 'Urgente'), ('CRITICA', 'Crítica')], default='INFORMATIVA', max_length=12)),
                ('estado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADA', 'Enviada'), ('LIDA', 'Lida'), ('RESOLVIDA', 'Resolvida'), ('FALHOU', 'Falhou')], default='PENDENTE', max_length=10)),
                ('limiar', models.CharField(blank=True, max_length=40)),
                ('chave_deduplicacao', models.CharField(max_length=180)),
                ('enviada_em', models.DateTimeField(blank=True, null=True)),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
                ('resolvida_em', models.DateTimeField(blank=True, null=True)),
                ('candidatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notificacoes', to='candidaturas.candidatura')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
                ('prazo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notificacoes', to='workflow.prazo')),
                ('tarefa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notificacoes', to='workflow.tarefa')),
            ],
            options={
                'verbose_name': 'notificação',
                'verbose_name_plural': 'notificações',
                'ordering': ('-criado_em',),
            },
        ),
        migrations.CreateModel(
            name='TermoAceitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('NAO_APLICAVEL', 'Não aplicável'), ('PENDENTE', 'Pendente'), ('RECEBIDO', 'Recebido'), ('VALIDADO', 'Validado'), ('INVALIDO', 'Inválido'), ('FORA_PRAZO', 'Fora de prazo'), ('DISPENSADO', 'Dispensado com justificação')], default='NAO_APLICAVEL', max_length=16)),
                ('notificado_em', models.DateTimeField(blank=True, null=True)),
                ('data_limite', models.DateTimeField(blank=True, null=True)),
                ('recebido_em', models.DateTimeField(blank=True, null=True)),
                ('validado_em', models.DateTimeField(blank=True, null=True)),
                ('tipo_assinatura', models.CharField(blank=True, choices=[('MANUSCRITA', 'Manuscrita'), ('DIGITAL_PESSOAL', 'Digital pessoal'), ('DIGITAL_PROFISSIONAL_SCAP', 'Digital profissional SCAP'), ('OUTRA', 'Outra')], max_length=26)),
                ('fora_prazo', models.BooleanField(default=False, editable=False)),
                ('justificacao', models.TextField(blank=True, verbose_name='justificação')),
                ('candidatura', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='termo_aceitacao', to='candidaturas.candidatura')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='termos_aceitacao', to='documentos.versaodocumento')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termos_aceitacao_validados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'termo de aceitação',
                'verbose_name_plural': 'termos de aceitação',
            },
        ),
        migrations.AddField(
            model_name='tarefa',
            name='termo_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarefas', to='workflow.termoaceitacao'),
        ),
        migrations.CreateModel(
            name='TransicaoCandidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, verbose_name='código')),
                ('estado_anterior', models.CharField(blank=True, choices=[('RASCUNHO', 'Rascunho'), ('PRONTA_SUBMISSAO', 'Pronta para submissão'), ('SUBMETIDA', 'Submetida'), ('EM_ANALISE', 'Em análise'), ('AGUARDA_ELEMENTOS', 'Aguarda elementos adicionais'), ('APROVADA_AGUARDA_TERMO', 'Aprovada — aguarda termo'), ('APROVADA_ACOMPANHAMENTO', 'Aprovada — em acompanhamento'), ('ENCERRAMENTO_PREPARACAO', 'Encerramento em preparação'), ('ENCERRAMENTO_SUBMETIDO', 'Encerramento submetido'), ('ENCERRAMENTO_ANALISE', 'Encerramento em análise'), ('ENCERRAMENTO_AGUARDA_ELEMENTOS', 'Encerramento aguarda elementos'), ('CONCLUIDA_AGUARDA_PAGAMENTO', 'Concluída — aguarda pagamento'), ('ENCERRADA', 'Encerrada'), ('INDEFERIDA', 'Indeferida'), ('ARQUIVADA', 'Arquivada pelo IEFP'), ('DESISTIDA', 'Desistida'), ('EXTINTA', 'Extinta'), ('REVOGADA', 'Revogada'), ('RASCUNHO_ARQUIVADO', 'Rascunho arquivado')], max_length=40, null=True)),
                ('estado_novo', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PRONTA_SUBMISSAO', 'Pronta para submissão'), ('SUBMETIDA', 'Submetida'), ('EM_ANALISE', 'Em análise'), ('AGUARDA_ELEMENTOS', 'Aguarda elementos adicionais'), ('APROVADA_AGUARDA_TERMO', 'Aprovada — aguarda termo'), ('APROVADA_ACOMPANHAMENTO', 'Aprovada — em acompanhamento'), ('ENCERRAMENTO_PREPARACAO', 'Encerramento em preparação'), ('ENCERRAMENTO_SUBMETIDO', 'Encerramento submetido'), ('ENCERRAMENTO_ANALISE', 'Encerramento em análise'), ('ENCERRAMENTO_AGUARDA_ELEMENTOS', 'Encerramento aguarda elementos'), ('CONCLUIDA_AGUARDA_PAGAMENTO', 'Concluída — aguarda pagamento'), ('ENCERRADA', 'Encerrada'), ('INDEFERIDA', 'Indeferida'), ('ARQUIVADA', 'Arquivada pelo IEFP'), ('DESISTIDA', 'Desistida'), ('EXTINTA', 'Extinta'), ('REVOGADA', 'Revogada'), ('RASCUNHO_ARQUIVADO', 'Rascunho arquivado')], max_length=40)),
                ('efetiva_em', models.DateTimeField()),
                ('registada_em', models.DateTimeField(auto_now_add=True)),
                ('origem', models.CharField(choices=[('UTILIZADOR', 'Utilizador'), ('SISTEMA', 'Sistema'), ('IEFPONLINE', 'Iefponline'), ('COMUNICACAO_IEFP', 'Comunicação do IEFP')], max_length=16)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, verbose_name='referência externa')),
                ('motivo', models.TextField(blank=True)),
                ('versao_anterior', models.PositiveIntegerField(editable=False)),
                ('versao_nova', models.PositiveIntegerField(editable=False)),
                ('chave_idempotencia', models.CharField(max_length=100)),
                ('ator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transicoes_candidatura_registadas', to=settings.AUTH_USER_MODEL)),
                ('beneficiario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transicoes', to='candidaturas.beneficiariocandidatura')),
                ('candidatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transicoes', to='candidaturas.candidatura')),
                ('conjunto_regras', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transicoes_candidatura', to='regras.conjuntoregras')),
                ('corrige_transicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correcoes', to='workflow.transicaocandidatura')),
                ('evidencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transicoes_comprovadas', to='documentos.versaodocumento')),
            ],
            options={
                'verbose_name': 'transição de candidatura',
                'verbose_name_plural': 'transições de candidaturas',
                'ordering': ('candidatura', 'registada_em', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='prazo',
            name='transicao_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prazos_criados', to='workflow.transicaocandidatura'),
        ),
        migrations.AddConstraint(
            model_name='pedidoelementos',
            constraint=models.UniqueConstraint(condition=models.Q(('referencia_externa', ''), _negated=True), fields=('candidatura', 'referencia_externa'), name='workflow_pedido_referencia_unica'),
        ),
        migrations.AddConstraint(
            model_name='pedidoelementos',
            constraint=models.CheckConstraint(condition=models.Q(('data_limite__gte', models.F('recebido_em'))), name='workflow_pedido_limite_valido'),
        ),
        migrations.AddConstraint(
            model_name='questaopedido',
            constraint=models.UniqueConstraint(fields=('pedido', 'ordem'), name='workflow_questao_ordem_unica'),
        ),
        migrations.AddConstraint(
            model_name='questaopedido',
            constraint=models.CheckConstraint(condition=models.Q(('ordem__gt', 0)), name='workflow_questao_ordem_positiva'),
        ),
        migrations.AddConstraint(
            model_name='questaopedido',
            constraint=models.CheckConstraint(condition=models.Q(('exige_texto', True), ('exige_documento', True), _connector='OR'), name='workflow_questao_exigencia_presente'),
        ),
        migrations.AddConstraint(
            model_name='respostaquestao',
            constraint=models.UniqueConstraint(fields=('questao', 'numero'), name='workflow_resposta_numero_unico'),
        ),
        migrations.AddConstraint(
            model_name='respostaquestao',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'SUBMETIDA')), fields=('questao',), name='workflow_resposta_submetida_unica'),
        ),
        migrations.AddConstraint(
            model_name='respostaquestao',
            constraint=models.CheckConstraint(condition=models.Q(('numero__gt', 0)), name='workflow_resposta_numero_positivo'),
        ),
        migrations.AddConstraint(
            model_name='suspensaoprazo',
            constraint=models.UniqueConstraint(condition=models.Q(('fim_em__isnull', True)), fields=('prazo',), name='workflow_suspensao_aberta_unica'),
        ),
        migrations.AddConstraint(
            model_name='suspensaoprazo',
            constraint=models.CheckConstraint(condition=models.Q(('fim_em__isnull', True), ('fim_em__gte', models.F('inicio_em')), _connector='OR'), name='workflow_suspensao_periodo_valido'),
        ),
        migrations.AddConstraint(
            model_name='notificacao',
            constraint=models.UniqueConstraint(fields=('destinatario', 'chave_deduplicacao'), name='workflow_notificacao_dedup_unica'),
        ),
        migrations.AddConstraint(
            model_name='tarefa',
            constraint=models.UniqueConstraint(condition=models.Q(('chave_deduplicacao__isnull', False), ('estado__in', ('ABERTA', 'EM_EXECUCAO'))), fields=('chave_deduplicacao',), name='workflow_tarefa_dedup_ativa'),
        ),
        migrations.AddIndex(
            model_name='transicaocandidatura',
            index=models.Index(fields=['candidatura', 'registada_em'], name='workflow_transicao_hist_idx'),
        ),
        migrations.AddConstraint(
            model_name='transicaocandidatura',
            constraint=models.UniqueConstraint(fields=('candidatura', 'chave_idempotencia'), name='workflow_transicao_idempotencia_unica'),
        ),
        migrations.AddConstraint(
            model_name='transicaocandidatura',
            constraint=models.CheckConstraint(condition=models.Q(('versao_nova', django.db.models.expressions.CombinedExpression(models.F('versao_anterior'), '+', models.Value(1)))), name='workflow_transicao_versao_sequencial'),
        ),
        migrations.AddConstraint(
            model_name='transicaocandidatura',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('codigo', 'TR-001'), ('estado_anterior__isnull', True)), models.Q(models.Q(('codigo', 'TR-001'), _negated=True), ('estado_anterior__isnull', False)), _connector='OR'), name='workflow_transicao_origem_coerente'),
        ),
        migrations.AddIndex(
            model_name='prazo',
            index=models.Index(fields=['estado', 'limite_calculado'], name='workflow_prazo_alerta_idx'),
        ),
        migrations.AddConstraint(
            model_name='prazo',
            constraint=models.CheckConstraint(condition=models.Q(('duracao__gt', 0)), name='workflow_prazo_duracao_positiva'),
        ),
        migrations.AddConstraint(
            model_name='prazo',
            constraint=models.CheckConstraint(condition=models.Q(('limite_calculado__gte', models.F('inicio_em'))), name='workflow_prazo_limite_valido'),
        ),
    ]
