# Generated by Django 5.2.17 on 2026-09-03 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidaturas', '0003_participacaoformacao_motivo_resultado'),
        ('documentos', '0002_snapshotsubmissao_transicao'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='prazo',
            index=models.Index(fields=['estado', 'limite_oficial'], name='workflow_prazo_oficial_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['destinatario', 'estado', 'criado_em'], name='workflow_notif_painel_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['atribuida_a', 'estado', 'data_limite'], name='workflow_tarefa_painel_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['candidatura', 'estado', 'data_limite'], name='workflow_tarefa_cand_idx'),
        ),
    ]
