# Generated by Django 5.2.17 on 2026-09-02 20:58

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0003_criar_grupos_iniciais'),
        ('formacoes', '0001_initial'),
        ('organizacoes', '0001_initial'),
        ('regras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('EMPRESARIAL', 'Empresarial')], max_length=12)),
                ('estado_atual', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PRONTA_SUBMISSAO', 'Pronta para submissão'), ('SUBMETIDA', 'Submetida'), ('EM_ANALISE', 'Em análise'), ('AGUARDA_ELEMENTOS', 'Aguarda elementos adicionais'), ('APROVADA_AGUARDA_TERMO', 'Aprovada — aguarda termo'), ('APROVADA_ACOMPANHAMENTO', 'Aprovada — em acompanhamento'), ('ENCERRAMENTO_PREPARACAO', 'Encerramento em preparação'), ('ENCERRAMENTO_SUBMETIDO', 'Encerramento submetido'), ('ENCERRAMENTO_ANALISE', 'Encerramento em análise'), ('ENCERRAMENTO_AGUARDA_ELEMENTOS', 'Encerramento aguarda elementos'), ('CONCLUIDA_AGUARDA_PAGAMENTO', 'Concluída — aguarda pagamento'), ('ENCERRADA', 'Encerrada'), ('INDEFERIDA', 'Indeferida'), ('ARQUIVADA', 'Arquivada pelo IEFP'), ('DESISTIDA', 'Desistida'), ('EXTINTA', 'Extinta'), ('REVOGADA', 'Revogada'), ('RASCUNHO_ARQUIVADO', 'Rascunho arquivado')], default='RASCUNHO', editable=False, max_length=40)),
                ('resultado_decisao', models.CharField(choices=[('PENDENTE', 'Pendente'), ('DEFERIDA_TOTAL', 'Deferida totalmente'), ('DEFERIDA_PARCIAL', 'Deferida parcialmente'), ('INDEFERIDA', 'Indeferida'), ('ARQUIVADA', 'Arquivada')], default='PENDENTE', editable=False, max_length=20)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('submetida_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('versao', models.PositiveIntegerField(default=1, editable=False, verbose_name='versão')),
                ('idempotencia_submissao', models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True)),
                ('conjunto_regras', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidaturas', to='regras.conjuntoregras')),
                ('conta_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidaturas', to='organizacoes.contapagamento')),
                ('criada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidaturas_criadas', to=settings.AUTH_USER_MODEL)),
                ('titular_candidato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidaturas_individuais', to='contas.perfilcandidato')),
                ('titular_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidaturas_empresariais', to='organizacoes.empresa')),
            ],
            options={
                'verbose_name': 'candidatura',
                'verbose_name_plural': 'candidaturas',
                'ordering': ('-criado_em',),
            },
        ),
        migrations.CreateModel(
            name='BeneficiarioCandidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('e_titular', models.BooleanField(default=False)),
                ('situacao_referencia', models.CharField(choices=[('CONTA_OUTREM', 'Trabalhador por conta de outrem'), ('CONTA_PROPRIA', 'Trabalhador por conta própria'), ('DESEMPREGADO', 'Desempregado')], max_length=20)),
                ('nivel_qualificacao_referencia', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('inscricao_iefp_referencia', models.DateField(blank=True, null=True)),
                ('resultado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('DEFERIDA', 'Deferida'), ('INDEFERIDA', 'Indeferida'), ('ARQUIVADA', 'Arquivada'), ('DESISTIDA', 'Desistida'), ('REVOGADA', 'Revogada'), ('ENCERRADA', 'Encerrada')], default='PENDENTE', max_length=12)),
                ('decidido_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_decisao', models.TextField(blank=True)),
                ('referencia_decisao', models.CharField(blank=True, max_length=100)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participacoes_candidatura', to='contas.perfilcandidato')),
                ('vinculo_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='beneficiarios_candidatura', to='organizacoes.vinculolaboral')),
                ('candidatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiarios', to='candidaturas.candidatura')),
            ],
            options={
                'verbose_name': 'beneficiário da candidatura',
                'verbose_name_plural': 'beneficiários da candidatura',
                'ordering': ('candidatura', 'candidato'),
            },
        ),
        migrations.CreateModel(
            name='AtribuicaoCandidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('papel', models.CharField(choices=[('RESPONSAVEL', 'Responsável'), ('COLABORADOR', 'Colaborador'), ('LEITURA', 'Leitura')], max_length=12)),
                ('principal', models.BooleanField(default=False)),
                ('ativa', models.BooleanField(default=True)),
                ('inicio_em', models.DateTimeField()),
                ('fim_em', models.DateTimeField(blank=True, null=True)),
                ('atribuida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atribuicoes_candidatura_criadas', to=settings.AUTH_USER_MODEL)),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atribuicoes_candidatura', to=settings.AUTH_USER_MODEL)),
                ('candidatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes', to='candidaturas.candidatura')),
            ],
            options={
                'verbose_name': 'atribuição de candidatura',
                'verbose_name_plural': 'atribuições de candidaturas',
                'ordering': ('candidatura', '-principal', 'utilizador'),
            },
        ),
        migrations.CreateModel(
            name='ParticipacaoFormacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('PLANEADA', 'Planeada'), ('EM_CURSO', 'Em curso'), ('CONCLUIDA_COM_APROVEITAMENTO', 'Concluída com aproveitamento'), ('CONCLUIDA_SEM_APROVEITAMENTO', 'Concluída sem aproveitamento'), ('INTERROMPIDA', 'Interrompida'), ('CANCELADA', 'Cancelada')], default='PLANEADA', max_length=40)),
                ('horas_previstas', models.DecimalField(decimal_places=2, max_digits=8)),
                ('horas_frequentadas', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dias_tres_ou_mais_horas', models.PositiveIntegerField(blank=True, null=True)),
                ('custo_declarado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('custo_pago_formadora', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('resultado_registado_em', models.DateTimeField(blank=True, null=True)),
                ('acao_formacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participacoes', to='formacoes.acaoformacao')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes_formacao', to='candidaturas.beneficiariocandidatura')),
            ],
            options={
                'verbose_name': 'participação em formação',
                'verbose_name_plural': 'participações em formação',
                'ordering': ('beneficiario', 'acao_formacao'),
            },
        ),
        migrations.CreateModel(
            name='VerificacaoElegibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo_regra', models.CharField(max_length=40, verbose_name='código da regra')),
                ('tipo_avaliacao', models.CharField(choices=[('AUTOMATICA', 'Automática'), ('MANUAL', 'Manual'), ('EXTERNA', 'Externa')], max_length=10)),
                ('resultado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFORME', 'Conforme'), ('NAO_CONFORME', 'Não conforme'), ('NAO_APLICAVEL', 'Não aplicável')], max_length=14)),
                ('valor_avaliado', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('verificada_em', models.DateTimeField(blank=True, null=True)),
                ('beneficiario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verificacoes_elegibilidade', to='candidaturas.beneficiariocandidatura')),
                ('candidatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificacoes_elegibilidade', to='candidaturas.candidatura')),
                ('participacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verificacoes_elegibilidade', to='candidaturas.participacaoformacao')),
                ('verificada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verificacoes_elegibilidade_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'verificação de elegibilidade',
                'verbose_name_plural': 'verificações de elegibilidade',
                'ordering': ('candidatura', 'codigo_regra', 'beneficiario', 'participacao'),
            },
        ),
        migrations.AddIndex(
            model_name='candidatura',
            index=models.Index(fields=['tipo', 'estado_atual'], name='cand_tipo_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatura',
            index=models.Index(fields=['titular_empresa', 'estado_atual'], name='cand_empresa_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatura',
            index=models.Index(fields=['titular_candidato', 'estado_atual'], name='cand_pessoa_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidatura',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'INDIVIDUAL'), ('titular_candidato__isnull', False), ('titular_empresa__isnull', True)), models.Q(('tipo', 'EMPRESARIAL'), ('titular_candidato__isnull', True), ('titular_empresa__isnull', False)), _connector='OR'), name='candidaturas_titular_coerente'),
        ),
        migrations.AddConstraint(
            model_name='candidatura',
            constraint=models.CheckConstraint(condition=models.Q(('versao__gt', 0)), name='candidaturas_versao_positiva'),
        ),
        migrations.AddIndex(
            model_name='beneficiariocandidatura',
            index=models.Index(fields=['candidatura', 'resultado'], name='cand_benef_resultado_idx'),
        ),
        migrations.AddConstraint(
            model_name='beneficiariocandidatura',
            constraint=models.UniqueConstraint(fields=('candidatura', 'candidato'), name='candidaturas_beneficiario_unico'),
        ),
        migrations.AddConstraint(
            model_name='beneficiariocandidatura',
            constraint=models.UniqueConstraint(condition=models.Q(('e_titular', True)), fields=('candidatura',), name='candidaturas_beneficiario_titular_unico'),
        ),
        migrations.AddConstraint(
            model_name='atribuicaocandidatura',
            constraint=models.UniqueConstraint(condition=models.Q(('ativa', True)), fields=('candidatura', 'utilizador'), name='candidaturas_atribuicao_ativa_unica'),
        ),
        migrations.AddConstraint(
            model_name='atribuicaocandidatura',
            constraint=models.UniqueConstraint(condition=models.Q(('ativa', True), ('principal', True)), fields=('candidatura',), name='candidaturas_responsavel_principal_unico'),
        ),
        migrations.AddConstraint(
            model_name='atribuicaocandidatura',
            constraint=models.CheckConstraint(condition=models.Q(('fim_em__isnull', True), ('fim_em__gte', models.F('inicio_em')), _connector='OR'), name='candidaturas_atribuicao_periodo_valido'),
        ),
        migrations.AddIndex(
            model_name='participacaoformacao',
            index=models.Index(fields=['beneficiario', 'estado'], name='cand_part_benef_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='participacaoformacao',
            index=models.Index(fields=['acao_formacao', 'estado'], name='cand_part_acao_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='participacaoformacao',
            constraint=models.UniqueConstraint(fields=('beneficiario', 'acao_formacao'), name='candidaturas_participacao_unica'),
        ),
        migrations.AddConstraint(
            model_name='participacaoformacao',
            constraint=models.CheckConstraint(condition=models.Q(('horas_previstas__gt', 0)), name='candidaturas_horas_previstas_positivas'),
        ),
        migrations.AddConstraint(
            model_name='participacaoformacao',
            constraint=models.CheckConstraint(condition=models.Q(('horas_frequentadas__isnull', True), ('horas_frequentadas__gte', 0), _connector='OR'), name='candidaturas_horas_frequentadas_nao_negativas'),
        ),
        migrations.AddConstraint(
            model_name='participacaoformacao',
            constraint=models.CheckConstraint(condition=models.Q(('custo_declarado__gte', 0)), name='candidaturas_custo_declarado_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='participacaoformacao',
            constraint=models.CheckConstraint(condition=models.Q(('custo_pago_formadora__isnull', True), ('custo_pago_formadora__gte', 0), _connector='OR'), name='candidaturas_custo_pago_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='verificacaoelegibilidade',
            constraint=models.UniqueConstraint(condition=models.Q(('beneficiario__isnull', True), ('participacao__isnull', True)), fields=('candidatura', 'codigo_regra'), name='candidaturas_verificacao_global_unica'),
        ),
        migrations.AddConstraint(
            model_name='verificacaoelegibilidade',
            constraint=models.UniqueConstraint(condition=models.Q(('beneficiario__isnull', False), ('participacao__isnull', True)), fields=('beneficiario', 'codigo_regra'), name='candidaturas_verificacao_benef_unica'),
        ),
        migrations.AddConstraint(
            model_name='verificacaoelegibilidade',
            constraint=models.UniqueConstraint(condition=models.Q(('participacao__isnull', False)), fields=('participacao', 'codigo_regra'), name='candidaturas_verificacao_part_unica'),
        ),
    ]
