# Generated by Django 5.2.17 on 2026-09-02 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidaturas', '0001_initial'),
        ('documentos', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificacaoelegibilidade',
            name='evidencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verificacoes_elegibilidade_comprovadas', to='documentos.versaodocumento'),
        ),
    ]
