# Generated by Django 5.2.17 on 2026-09-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidaturas", "0002_verificacaoelegibilidade_evidencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="participacaoformacao",
            name="motivo_resultado",
            field=models.TextField(blank=True),
        ),
    ]
