# Generated by Django 5.2.17 on 2026-09-02 20:09

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=80, unique=True, verbose_name='código')),
                ('designacao', models.CharField(max_length=255, verbose_name='designação')),
                ('categoria', models.CharField(choices=[('IDENTIDADE', 'Identidade'), ('EMPRESA', 'Empresa'), ('EMPREGO', 'Emprego'), ('FORMACAO', 'Formação'), ('FINANCEIRO', 'Financeiro'), ('DECISAO', 'Decisão'), ('OUTRO', 'Outro')], max_length=12)),
                ('sensibilidade', models.CharField(choices=[('INTERNO', 'Interno'), ('PESSOAL', 'Pessoal'), ('PESSOAL_SENSIVEL', 'Pessoal sensível')], max_length=18)),
                ('tem_validade', models.BooleanField(default=False)),
                ('apenas_pdf', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'tipo de documento',
                'verbose_name_plural': 'tipos de documentos',
                'ordering': ('categoria', 'designacao'),
            },
        ),
        migrations.CreateModel(
            name='ConjuntoRegras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=50, verbose_name='código')),
                ('versao', models.PositiveIntegerField(verbose_name='versão')),
                ('designacao', models.CharField(max_length=255, verbose_name='designação')),
                ('estado', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ATIVO', 'Ativo'), ('SUBSTITUIDO', 'Substituído'), ('ARQUIVADO', 'Arquivado')], default='RASCUNHO', max_length=20)),
                ('vigente_desde', models.DateField()),
                ('vigente_ate', models.DateField(blank=True, null=True)),
                ('referencia_demonstracao', models.BooleanField(default=True, verbose_name='referência de demonstração')),
                ('fonte', models.TextField()),
                ('publicado_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('publicado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conjuntos_regras_publicados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'conjunto de regras',
                'verbose_name_plural': 'conjuntos de regras',
                'ordering': ('codigo', '-versao'),
            },
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data', models.DateField()),
                ('designacao', models.CharField(max_length=150, verbose_name='designação')),
                ('ambito', models.CharField(choices=[('NACIONAL', 'Nacional'), ('REGIONAL', 'Regional'), ('MUNICIPAL', 'Municipal')], max_length=10, verbose_name='âmbito')),
                ('regiao', models.CharField(blank=True, max_length=120, verbose_name='região')),
                ('ativo', models.BooleanField(default=True)),
                ('fonte', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'feriado',
                'verbose_name_plural': 'feriados',
                'ordering': ('data', 'ambito', 'regiao'),
                'constraints': [models.UniqueConstraint(fields=('data', 'ambito', 'regiao'), name='regras_feriado_data_ambito_regiao_unicos'), models.CheckConstraint(condition=models.Q(models.Q(('ambito', 'NACIONAL'), ('regiao', '')), models.Q(models.Q(('ambito', 'NACIONAL'), _negated=True), models.Q(('regiao', ''), _negated=True)), _connector='OR'), name='regras_feriado_regiao_coerente')],
            },
        ),
        migrations.CreateModel(
            name='ParametroRegra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=80, verbose_name='código')),
                ('designacao', models.CharField(max_length=255, verbose_name='designação')),
                ('tipo_valor', models.CharField(choices=[('INTEIRO', 'Inteiro'), ('DECIMAL', 'Decimal'), ('BOOLEANO', 'Booleano'), ('TEXTO', 'Texto'), ('DATA', 'Data'), ('JSON', 'JSON')], max_length=10)),
                ('valor', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('unidade', models.CharField(blank=True, max_length=40)),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('conjunto_regras', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parametros', to='regras.conjuntoregras')),
            ],
            options={
                'verbose_name': 'parâmetro de regra',
                'verbose_name_plural': 'parâmetros de regras',
                'ordering': ('conjunto_regras', 'codigo'),
            },
        ),
        migrations.AddConstraint(
            model_name='conjuntoregras',
            constraint=models.UniqueConstraint(fields=('codigo', 'versao'), name='regras_conjunto_codigo_versao_unicos'),
        ),
        migrations.AddConstraint(
            model_name='conjuntoregras',
            constraint=models.CheckConstraint(condition=models.Q(('versao__gt', 0)), name='regras_conjunto_versao_positiva'),
        ),
        migrations.AddConstraint(
            model_name='conjuntoregras',
            constraint=models.CheckConstraint(condition=models.Q(('vigente_ate__isnull', True), ('vigente_ate__gte', models.F('vigente_desde')), _connector='OR'), name='regras_conjunto_vigencia_valida'),
        ),
        migrations.AddConstraint(
            model_name='parametroregra',
            constraint=models.UniqueConstraint(fields=('conjunto_regras', 'codigo'), name='regras_parametro_codigo_unico_no_conjunto'),
        ),
    ]
