# Generated by Django 5.2.17 on 2026-09-02 21:34

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidaturas', '0001_initial'),
        ('regras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheiroArmazenado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_armazenamento', models.CharField(editable=False, max_length=500, unique=True)),
                ('nome_original', models.CharField(editable=False, max_length=255)),
                ('tipo_mime', models.CharField(editable=False, max_length=100)),
                ('tamanho_bytes', models.PositiveBigIntegerField(editable=False)),
                ('sha256', models.CharField(editable=False, max_length=64)),
                ('estado_upload', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDO', 'Concluído'), ('FALHOU', 'Falhou'), ('REMOVIDO', 'Removido')], default='PENDENTE', editable=False, max_length=10)),
                ('estado_seguranca', models.CharField(choices=[('PENDENTE', 'Pendente'), ('SEGURO', 'Seguro'), ('SUSPEITO', 'Suspeito'), ('BLOQUEADO', 'Bloqueado')], default='PENDENTE', editable=False, max_length=10)),
                ('carregado_em', models.DateTimeField(auto_now_add=True)),
                ('removido_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('carregado_por', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='ficheiros_carregados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ficheiro armazenado',
                'verbose_name_plural': 'ficheiros armazenados',
                'ordering': ('-carregado_em',),
            },
        ),
        migrations.CreateModel(
            name='RequisitoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fase', models.CharField(choices=[('PREPARACAO', 'Preparação'), ('ANALISE', 'Análise'), ('ACEITACAO', 'Aceitação'), ('ACOMPANHAMENTO', 'Acompanhamento'), ('ENCERRAMENTO', 'Encerramento'), ('FINANCEIRA', 'Financeira')], max_length=16)),
                ('codigo_regra', models.CharField(blank=True, max_length=40, verbose_name='código da regra')),
                ('obrigatorio', models.BooleanField(default=True)),
                ('bloqueante', models.BooleanField(default=True)),
                ('data_limite', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('EM_FALTA', 'Em falta'), ('RECEBIDO', 'Recebido'), ('EM_VALIDACAO', 'Em validação'), ('VALIDO', 'Válido'), ('INVALIDO', 'Inválido'), ('DISPENSADO', 'Dispensado com justificação')], default='EM_FALTA', editable=False, max_length=12)),
                ('dispensado_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('motivo_dispensa', models.TextField(blank=True, editable=False)),
                ('beneficiario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_documentais', to='candidaturas.beneficiariocandidatura')),
                ('candidatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_documentais', to='candidaturas.candidatura')),
                ('dispensado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitos_documentais_dispensados', to=settings.AUTH_USER_MODEL)),
                ('participacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_documentais', to='candidaturas.participacaoformacao')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitos', to='regras.tipodocumento')),
            ],
            options={
                'verbose_name': 'requisito documental',
                'verbose_name_plural': 'requisitos documentais',
                'ordering': ('fase', 'beneficiario', 'participacao', 'tipo_documento'),
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fase', models.CharField(choices=[('PREPARACAO', 'Preparação'), ('ANALISE', 'Análise'), ('ACEITACAO', 'Aceitação'), ('ACOMPANHAMENTO', 'Acompanhamento'), ('ENCERRAMENTO', 'Encerramento'), ('FINANCEIRA', 'Financeira')], max_length=16)),
                ('titulo', models.CharField(blank=True, max_length=255, verbose_name='título')),
                ('estado_atual', models.CharField(choices=[('EM_FALTA', 'Em falta'), ('RECEBIDO', 'Recebido'), ('EM_VALIDACAO', 'Em validação'), ('VALIDO', 'Válido'), ('INVALIDO', 'Inválido'), ('DISPENSADO', 'Dispensado com justificação')], default='RECEBIDO', editable=False, max_length=12)),
                ('beneficiario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='candidaturas.beneficiariocandidatura')),
                ('candidatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='candidaturas.candidatura')),
                ('criado_por', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_criados', to=settings.AUTH_USER_MODEL)),
                ('participacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='candidaturas.participacaoformacao')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='regras.tipodocumento')),
                ('requisito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='documentos.requisitodocumento')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ('candidatura', 'fase', 'tipo_documento'),
            },
        ),
        migrations.CreateModel(
            name='VersaoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(editable=False)),
                ('estado_validacao', models.CharField(choices=[('RECEBIDO', 'Recebido'), ('EM_VALIDACAO', 'Em validação'), ('VALIDO', 'Válido'), ('INVALIDO', 'Inválido'), ('SUBSTITUIDO', 'Substituído')], default='RECEBIDO', editable=False, max_length=12)),
                ('corrente', models.BooleanField(default=True, editable=False)),
                ('emitido_em', models.DateField(blank=True, null=True)),
                ('valido_ate', models.DateField(blank=True, null=True)),
                ('carregada_em', models.DateTimeField(auto_now_add=True)),
                ('validada_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('observacao_validacao', models.TextField(blank=True, editable=False, verbose_name='observação da validação')),
                ('motivo_substituicao', models.TextField(blank=True, editable=False, verbose_name='motivo da substituição')),
                ('carregada_por', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='versoes_documentais_carregadas', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versoes', to='documentos.documento')),
                ('ficheiro', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='versao_documento', to='documentos.ficheiroarmazenado')),
                ('validada_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versoes_documentais_validadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'versão de documento',
                'verbose_name_plural': 'versões de documentos',
                'ordering': ('documento', '-numero'),
            },
        ),
        migrations.CreateModel(
            name='SnapshotSubmissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalidade', models.CharField(choices=[('SUBMISSAO', 'Submissão'), ('TERMO', 'Termo'), ('ENCERRAMENTO', 'Encerramento'), ('CORRECAO', 'Correção')], max_length=12)),
                ('sequencia', models.PositiveIntegerField(editable=False)),
                ('capturado_em', models.DateTimeField(auto_now_add=True)),
                ('dados', models.JSONField(editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('versao_esquema', models.PositiveIntegerField(default=1, editable=False)),
                ('hash_conteudo', models.CharField(editable=False, max_length=64)),
                ('candidatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots_submissao', to='candidaturas.candidatura')),
                ('capturado_por', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='snapshots_capturados', to=settings.AUTH_USER_MODEL)),
                ('versoes_documentos', models.ManyToManyField(blank=True, related_name='snapshots_submissao', to='documentos.versaodocumento')),
            ],
            options={
                'verbose_name': 'snapshot de submissão',
                'verbose_name_plural': 'snapshots de submissão',
                'ordering': ('candidatura', 'finalidade', '-sequencia'),
            },
        ),
        migrations.AddConstraint(
            model_name='ficheiroarmazenado',
            constraint=models.CheckConstraint(condition=models.Q(('tamanho_bytes__gte', 0)), name='documentos_ficheiro_tamanho_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='requisitodocumento',
            constraint=models.UniqueConstraint(condition=models.Q(('beneficiario__isnull', True), ('participacao__isnull', True)), fields=('candidatura', 'tipo_documento', 'fase'), name='documentos_requisito_global_unico'),
        ),
        migrations.AddConstraint(
            model_name='requisitodocumento',
            constraint=models.UniqueConstraint(condition=models.Q(('beneficiario__isnull', False), ('participacao__isnull', True)), fields=('beneficiario', 'tipo_documento', 'fase'), name='documentos_requisito_benef_unico'),
        ),
        migrations.AddConstraint(
            model_name='requisitodocumento',
            constraint=models.UniqueConstraint(condition=models.Q(('participacao__isnull', False)), fields=('participacao', 'tipo_documento', 'fase'), name='documentos_requisito_part_unico'),
        ),
        migrations.AddConstraint(
            model_name='documento',
            constraint=models.UniqueConstraint(condition=models.Q(('requisito__isnull', False)), fields=('requisito',), name='documentos_documento_por_requisito_unico'),
        ),
        migrations.AddConstraint(
            model_name='versaodocumento',
            constraint=models.UniqueConstraint(fields=('documento', 'numero'), name='documentos_versao_numero_unico'),
        ),
        migrations.AddConstraint(
            model_name='versaodocumento',
            constraint=models.UniqueConstraint(condition=models.Q(('corrente', True)), fields=('documento',), name='documentos_versao_corrente_unica'),
        ),
        migrations.AddConstraint(
            model_name='versaodocumento',
            constraint=models.CheckConstraint(condition=models.Q(('numero__gt', 0)), name='documentos_versao_numero_positivo'),
        ),
        migrations.AddConstraint(
            model_name='versaodocumento',
            constraint=models.CheckConstraint(condition=models.Q(('valido_ate__isnull', True), ('emitido_em__isnull', True), ('valido_ate__gte', models.F('emitido_em')), _connector='OR'), name='documentos_versao_validade_coerente'),
        ),
        migrations.AddConstraint(
            model_name='snapshotsubmissao',
            constraint=models.UniqueConstraint(fields=('candidatura', 'finalidade', 'sequencia'), name='documentos_snapshot_sequencia_unica'),
        ),
        migrations.AddConstraint(
            model_name='snapshotsubmissao',
            constraint=models.CheckConstraint(condition=models.Q(('sequencia__gt', 0)), name='documentos_snapshot_sequencia_positiva'),
        ),
        migrations.AddConstraint(
            model_name='snapshotsubmissao',
            constraint=models.CheckConstraint(condition=models.Q(('versao_esquema__gt', 0)), name='documentos_snapshot_esquema_positivo'),
        ),
    ]
