# Generated by Django 5.2.17 on 2026-09-02 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshotsubmissao',
            name='transicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='snapshots_submissao', to='workflow.transicaocandidatura'),
        ),
    ]
