# Generated by Django 5.2.17 on 2026-09-02 20:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoFormacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('referencia_externa', models.CharField(blank=True, max_length=100)),
                ('designacao', models.CharField(max_length=255, verbose_name='designação')),
                ('area_codigo', models.CharField(blank=True, max_length=20, verbose_name='código da área')),
                ('area_designacao', models.CharField(blank=True, max_length=255, verbose_name='designação da área')),
                ('modalidade', models.CharField(blank=True, max_length=120)),
                ('tipologia', models.CharField(blank=True, choices=[('', 'Por definir'), ('CNQ', 'CNQ'), ('EXTRA_CNQ', 'Extra-CNQ'), ('MISTA', 'Mista')], default='', editable=False, max_length=10)),
                ('inicio_previsto', models.DateField(verbose_name='início previsto')),
                ('fim_previsto', models.DateField(verbose_name='fim previsto')),
                ('inicio_real', models.DateField(blank=True, null=True, verbose_name='início real')),
                ('fim_real', models.DateField(blank=True, null=True, verbose_name='fim real')),
                ('local', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('PLANEADA', 'Planeada'), ('EM_CURSO', 'Em curso'), ('CONCLUIDA_COM_APROVEITAMENTO', 'Concluída com aproveitamento'), ('CONCLUIDA_SEM_APROVEITAMENTO', 'Concluída sem aproveitamento'), ('INTERROMPIDA', 'Interrompida'), ('CANCELADA', 'Cancelada')], default='PLANEADA', max_length=40)),
                ('horas_totais', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=8)),
                ('entidade_formadora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acoes_formacao', to='organizacoes.entidadeformadora')),
            ],
            options={
                'verbose_name': 'ação de formação',
                'verbose_name_plural': 'ações de formação',
                'ordering': ('-inicio_previsto', 'designacao'),
            },
        ),
        migrations.CreateModel(
            name='ComponenteFormacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ordem', models.PositiveSmallIntegerField()),
                ('tipo', models.CharField(choices=[('CNQ', 'CNQ'), ('EXTRA_CNQ', 'Extra-CNQ')], max_length=10)),
                ('codigo_cnq', models.CharField(blank=True, max_length=30, verbose_name='código CNQ')),
                ('designacao', models.CharField(max_length=255, verbose_name='designação')),
                ('area_codigo', models.CharField(blank=True, max_length=20, verbose_name='código da área')),
                ('referencial', models.CharField(blank=True, max_length=255)),
                ('horas', models.DecimalField(decimal_places=2, max_digits=8)),
                ('justificacao_extra_cnq', models.TextField(blank=True, verbose_name='justificação extra-CNQ')),
                ('acao_formacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='formacoes.acaoformacao')),
            ],
            options={
                'verbose_name': 'componente de formação',
                'verbose_name_plural': 'componentes de formação',
                'ordering': ('acao_formacao', 'ordem'),
            },
        ),
        migrations.AddConstraint(
            model_name='acaoformacao',
            constraint=models.CheckConstraint(condition=models.Q(('fim_previsto__gte', models.F('inicio_previsto'))), name='formacoes_acao_periodo_previsto_valido'),
        ),
        migrations.AddConstraint(
            model_name='acaoformacao',
            constraint=models.CheckConstraint(condition=models.Q(('horas_totais__gte', 0)), name='formacoes_acao_horas_nao_negativas'),
        ),
        migrations.AddConstraint(
            model_name='componenteformacao',
            constraint=models.UniqueConstraint(fields=('acao_formacao', 'ordem'), name='formacoes_componente_ordem_unica'),
        ),
        migrations.AddConstraint(
            model_name='componenteformacao',
            constraint=models.CheckConstraint(condition=models.Q(('ordem__gt', 0)), name='formacoes_componente_ordem_positiva'),
        ),
        migrations.AddConstraint(
            model_name='componenteformacao',
            constraint=models.CheckConstraint(condition=models.Q(('horas__gt', 0)), name='formacoes_componente_horas_positivas'),
        ),
    ]
