# Generated by Django 5.2.17 on 2026-09-03 13:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=100, verbose_name='ação')),
                ('tipo_objeto', models.CharField(max_length=100)),
                ('id_objeto', models.CharField(blank=True, max_length=100)),
                ('public_id_objeto', models.UUIDField(blank=True, null=True)),
                ('ocorrido_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('resultado', models.CharField(choices=[('SUCESSO', 'Sucesso'), ('RECUSADO', 'Recusado'), ('ERRO', 'Erro')], max_length=10)),
                ('id_pedido', models.CharField(blank=True, max_length=100)),
                ('id_correlacao', models.CharField(blank=True, max_length=100)),
                ('hash_ip', models.CharField(blank=True, max_length=64)),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('utilizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registos_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registo de auditoria',
                'verbose_name_plural': 'registos de auditoria',
                'ordering': ('-ocorrido_em', '-pk'),
                'indexes': [models.Index(fields=['acao', 'ocorrido_em'], name='auditoria_acao_data_idx'), models.Index(fields=['tipo_objeto', 'public_id_objeto'], name='auditoria_objeto_publico_idx')],
            },
        ),
    ]
